# Generated by Django 5.0.1 on 2024-01-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["-title", "order"],
                "verbose_name": "pagina",
                "verbose_name_plural": "paginas",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.SmallIntegerField(default=0, verbose_name="Orden"),
        ),
    ]
