# Generated by Django 5.0.1 on 2024-01-22 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 22, 15, 6, 59, 242328, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de publicacion",
            ),
        ),
    ]
